- name: Set MOTD
  template:
    src: templates/motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: 0444

- name: Read contents of motd
  command: cat /etc/motd
  register: file_content

- name: Display the Contents
  debug:
    msg: "{{ file_content.stdout_lines }}"
