---

    - name: Install Fail2Ban
      apt:
        name: fail2ban
        state: present

    - name: Copy Fail2Ban configuration file
      template:
        src: templates/jail.conf.j2
        dest: /etc/fail2ban/jail.local

    - name: Restart Fail2Ban
      service:
        name: fail2ban
        state: restarted
